name: analyticcenter
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.6
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - colorlog=4.0.2
  - control=0.8.2
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=58.2
  - jpeg=9c
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - ncurses=6.1
  - numpy=1.16.4
  - openblas=0.3.5
  - openssl=1.1.1b
  - pcre=8.41
  - pip=19.1.1
  - pthread-stubs=0.4
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.7.3
  - python-dateutil=2.8.0
  - pyyaml=5.1.1
  - qt=5.9.7
  - readline=7.0
  - scipy=1.3.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - slycot=0.3.3
  - sqlite=3.28.0
  - tk=8.6.9
  - tornado=6.0.2
  - wheel=0.33.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
