name: analyticcenter
channels:
  - conda-forge
  - dbankmann
  - defaults
dependencies:
  - analyticcenter=0.3.0
  - bzip2
  - ca-certificates
  - certifi
  - colorlog
  - control
  - cycler
  - dbus
  - expat
  - fontconfig
  - freetype
  - gettext
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - jpeg
  - kiwisolver
  - libblas
  - libcblas
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - liblapack
  - libpng
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libxml2
  - matplotlib
  - matplotlib-base
  - ncurses
  - numpy
  - openblas
  - openssl
  - pcre
  - pip
  - pthread-stubs
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pyyaml
  - qt
  - readline
  - scipy
  - setuptools
  - sip
  - six
  - slycot
  - sqlite
  - tk
  - tornado
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zlib
