package:
     name: analyticcenter
     version: {{ GIT_DESCRIBE_TAG }}

source:
     git_url: ../

channels:
        - conda-forge
        - defaults
build:
     noarch: python
     number: {{GIT_DESCRIBE_NUMBER}}
     script:
          - cd $RECIPE_DIR/..
          - "$PYTHON -m pip install --no-deps . -vv"
requirements:
     build: 
         - pytest
     run:
         - numpy >=1.13.3
         - scipy
         - control>=0.7.0
         - colorlog>=2.10.0
         - matplotlib>=2.0.0
         - PyYAML>=3.12
         - slycot>=0.3.3
         - pytest-runner

about:
     home: https://gitlab.tubit.tu-berlin.de/PassivityRadius/analyticcenter
     license:  BSD 3 License
     summary: "Python library for computing the analytic center of the passivity LMI"

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

test:
  requirements:
          - pytest


