---

version: 1
disable_existing_loggers: False
formatters:
    console:
        class: colorlog.ColoredFormatter
        format: "%(log_color)s[%(levelname)-8s][%(name)s] --- %(message)s (%(filename)s:%(lineno)s)"
        datefmt: "%Y-%m-%d %H:%M:%S"
        log_colors=:
          DEBUG: 'red'
          INFO: 'green'
          WARNING: 'yellow'
          ERROR: 'red'
          CRITICAL: 'red,bg_white'

    console_user:
        class: colorlog.ColoredFormatter
        format: "%(log_color)s[%(levelname)-8s][%(name)s] --- %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
        log_colors=:
          DEBUG: 'red'
          INFO: 'green'
          WARNING: 'yellow'
          ERROR: 'red'
          CRITICAL: 'red,bg_white'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: console
        stream: ext://sys.stdout
    console_user:
        class: logging.StreamHandler
        level: INFO
        formatter: console_user
        stream: ext://sys.stdout


root:
    level: DEBUG
    handlers: []
loggers:
    debug:
        level: DEBUG
        handlers: [console]

    user:
        level: INFO
        handlers: [console_user]
